FROM mysql:8.0

# Variables de entorno para MySQL
ENV MYSQL_ROOT_PASSWORD=passwordRoot
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=usernormal
ENV MYSQL_PASSWORD=root

# Exponer el puerto de MySQLx
EXPOSE 3306